apiVersion: v1
kind: Secret
metadata:
  name: root
  annotations:
    avp.kubernetes.io/kv-version: "2"
    avp.kubernetes.io/secret-version: "1"
    avp.kubernetes.io/path: "secret/data/affiliate/admin-api"
type: Opaque
stringData:
  TOKEN: <APP_HOST>
