apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: new-test
  namespace: argocd
  annotations:
    avp.kubernetes.io/path: "kv-v2/data/argocd"
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: metrics-server
    repoURL: https://kubernetes-sigs.github.io/metrics-server
    targetRevision: 3.11.0
    helm:
      values: |
        replicas: <password>
